spring:
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/tickets
    username: root
    password: 1234
